### ISSUE TITLE
Error message isn't correctly formatted

### ISSUE THREAD

**Issue by Calinou** [intoli/exodus#14]
**Operating system, Python and Exodus version:** Fedora 27, Python 3.6.4, Exodus 1.1.6

The error message about a binary not being in `$PATH` isn't actually formatted, so the `%s` is always visible.

Non-verbose output:

```
❯ exodus non-existing_binary
ERROR: Fatal error encountered, exiting.
ERROR: The "%s" binary could not be found in $PATH.
```

Verbose output:

```
❯ exodus non-existing_binary -v
ERROR: Fatal error encountered, exiting.
ERROR: The "%s" binary could not be found in $PATH.
Traceback (most recent call last):
  File "/home/hugo/.local/lib/python3.6/site-packages/exodus_bundler/cli.py", line 118, in main
    create_bundle(**args)
  File "/home/hugo/.local/lib/python3.6/site-packages/exodus_bundler/bundling.py", line 34, in create_bundle
    root_directory = create_unpackaged_bundle(executables, rename=rename, ldd=ldd)
  File "/home/hugo/.local/lib/python3.6/site-packages/exodus_bundler/bundling.py", line 100, in create_unpackaged_bundle
    for name, executable in zip(rename, map(resolve_binary, executables)):
  File "/home/hugo/.local/lib/python3.6/site-packages/exodus_bundler/bundling.py", line 217, in resolve_binary
    raise MissingFileError('The "%s" binary could not be found in $PATH.')
exodus_bundler.errors.MissingFileError: The "%s" binary could not be found in $PATH.
```

**Comment by sangaline** [comment]
Thanks for reporting this!
