### ISSUE TITLE
FileNotFoundError('"%s" is not a file.')

### ISSUE THREAD

**Issue by rakhimov** [Intoli/exodus#5]
On Ubuntu 16.04, following the example in readme:

```bash
> exodus htop

Traceback (most recent call last):
  File "/.../.local/bin/exodus-bundler", line 11, in <module>
    sys.exit(main())
  File "/.../.local/lib/python3.5/site-packages/exodus_bundler/cli.py", line 113, in main
    create_bundle(**args)
  File "/.../.local/lib/python3.5/site-packages/exodus_bundler/bundling.py", line 32, in create_bundle
    root_directory = create_unpackaged_bundle(executables, rename=rename, ldd=ldd)
  File "/.../.local/lib/python3.5/site-packages/exodus_bundler/bundling.py", line 109, in create_unpackaged_bundle
    dependencies = find_all_library_dependencies(ldd, executable)
  File "/.../.local/lib/python3.5/site-packages/exodus_bundler/bundling.py", line 170, in find_all_library_dependencies
    new_dependencies |= set(find_direct_library_dependencies(ldd, dependency))
  File "/.../.local/lib/python3.5/site-packages/exodus_bundler/bundling.py", line 177, in find_direct_library_dependencies
    matches = filter(None, (re.search('=>\s*([^(]*?)\s*\(', line) for line in run_ldd(ldd, binary)))
  File "/.../.local/lib/python3.5/site-packages/exodus_bundler/bundling.py", line 194, in run_ldd
    raise FileNotFoundError('"%s" is not a file.')
FileNotFoundError: "%s" is not a file.
```

**Comment by jchmielarz** [comment]
Same thing on 17.10

**Comment by sangaline** [comment]
Could you post the output of `which htop` and `echo $PATH`? This is what I would expect if you don't have an `htop` binary in your `PATH`. I'll add better handling and logging of these sort of errors in #9.

**Comment by sangaline** [comment]
@rakhimov and @jchmielarz - Could you let me know if you're still experiencing this behavior with v1.1.3 or above?

**Comment by jchmielarz** [comment]
This issue seems to be fixed for me.

**Comment by sangaline** [comment]
@jchmielarz Great, thanks for reporting back!
