### ISSUE TITLE
AssertionError: No linker candidates found.

### ISSUE THREAD

**Issue by rakhimov** [Intoli/exodus#6]
on Ubuntu 16.04,
```bash
> which ldd
/usr/bin/ldd
> exodus ldd
Traceback (most recent call last):
  File "/.../.local/bin/exodus", line 11, in <module>
    sys.exit(main())
  File "/.../.local/lib/python2.7/site-packages/exodus_bundler/cli.py", line 113, in main
    create_bundle(**args)
  File "/.../.local/lib/python2.7/site-packages/exodus_bundler/bundling.py", line 32, in create_bundle
    root_directory = create_unpackaged_bundle(executables, rename=rename, ldd=ldd)
  File "/.../.local/lib/python2.7/site-packages/exodus_bundler/bundling.py", line 133, in create_unpackaged_bundle
    assert len(linker_candidates) > 0, 'No linker candidates found.'
AssertionError: No linker candidates found.
```

**Comment by sangaline** [comment]
You're getting this error because `ldd` is a shell script and exodus only supports bundling ELF binaries. There should definitely be a more informative error message here though. I've created #9 to address this.
